/*
 * router.c — match path → handler.
 *
 *   GET /             → serve embedded index.html
 *   GET /game         → SSE stream of frames for this session
 *   GET /input?key=X  → mutate session state, return 204
 *   GET /restart      → reset session state, return 204
 *   GET /healthz      → 200 ok, for the load balancer
 *
 * sessions are tracked via the `crypt_sid` cookie. if the request has none
 * we mint one and Set-Cookie on the way out.
 */

#include "router.h"
#include "server.h"
#include "session.h"
#include "render.h"
#include "game.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

/* generated by xxd -i from static/index.html — provides:
 *   unsigned char index_html[];
 *   unsigned int  index_html_len;
 */
#include "static_html.h"

#define COOKIE_NAME "crypt_sid"

static void parse_cookie_for_sid(const char *cookie_header, char *out_sid, size_t cap) {
    out_sid[0] = '\0';
    if (!cookie_header || !*cookie_header) return;
    /* find COOKIE_NAME=... */
    const char *p = cookie_header;
    size_t klen = strlen(COOKIE_NAME);
    while (*p) {
        while (*p == ' ' || *p == ';') p++;
        if (!*p) break;
        if (strncmp(p, COOKIE_NAME, klen) == 0 && p[klen] == '=') {
            const char *v = p + klen + 1;
            size_t i = 0;
            while (*v && *v != ';' && i + 1 < cap) out_sid[i++] = *v++;
            out_sid[i] = '\0';
            return;
        }
        while (*p && *p != ';') p++;
    }
}

/* simple key=value query parser, single key only */
static int query_get(const char *query, const char *key, char *out, size_t cap) {
    out[0] = '\0';
    if (!query || !*query) return 0;
    size_t klen = strlen(key);
    const char *p = query;
    while (*p) {
        if (strncmp(p, key, klen) == 0 && p[klen] == '=') {
            const char *v = p + klen + 1;
            size_t i = 0;
            while (*v && *v != '&' && i + 1 < cap) out[i++] = *v++;
            out[i] = '\0';
            return 1;
        }
        while (*p && *p != '&') p++;
        while (*p == '&') p++;
    }
    return 0;
}

/* %20 → ' ', '+' → ' ', %hh → byte. anything else is copied. */
static void url_decode(const char *src, char *dst, size_t cap) {
    size_t i = 0;
    while (*src && i + 1 < cap) {
        if (*src == '%' && src[1] && src[2]) {
            char hex[3] = { src[1], src[2], 0 };
            dst[i++] = (char)strtol(hex, NULL, 16);
            src += 3;
        } else if (*src == '+') {
            dst[i++] = ' '; src++;
        } else {
            dst[i++] = *src++;
        }
    }
    dst[i] = '\0';
}

/* ---- handlers --------------------------------------------------------- */

static int handle_index(int fd) {
    return respond_simple(fd, 200, "OK",
                          "text/html; charset=utf-8",
                          (const char *)index_html, (size_t)index_html_len,
                          NULL);
}

static int handle_health(int fd) {
    static const char *body = "ok\n";
    return respond_simple(fd, 200, "OK", "text/plain", body, 3, NULL);
}

/* find or create the session for this request. if newly created, *new_cookie
 * is filled with a Set-Cookie header line (with trailing CRLF) for the
 * caller to send. otherwise *new_cookie[0] = 0. */
static Session *resolve_session(Request *r, char *new_cookie, size_t cap) {
    new_cookie[0] = '\0';
    char sid[SID_LEN + 1];
    parse_cookie_for_sid(r->cookie, sid, sizeof sid);
    Session *s = session_find(sid);
    if (s) return s;

    char fresh[SID_LEN + 1];
    s = session_create(fresh);
    snprintf(new_cookie, cap,
             "Set-Cookie: %s=%s; Path=/; Max-Age=86400; SameSite=Lax\r\n",
             COOKIE_NAME, fresh);
    return s;
}

static int handle_input(int fd, Request *r) {
    char cookie[256];
    Session *s = resolve_session(r, cookie, sizeof cookie);
    if (!s) return respond_simple(fd, 500, "Internal Error", "text/plain",
                                  "no session\n", 11, NULL);

    char raw[16] = {0};
    if (!query_get(r->query, "key", raw, sizeof raw)) {
        return respond_simple(fd, 400, "Bad Request", "text/plain",
                              "missing key\n", 12, cookie[0] ? cookie : NULL);
    }
    char decoded[16] = {0};
    url_decode(raw, decoded, sizeof decoded);

    session_lock(s);
    game_apply_input(s->state, decoded[0]);
    session_bump_locked(s);
    session_unlock(s);

    /* 204 with no body is fine; some browsers complain about content-length
     * with 204 so emit an empty body via 200 instead. */
    return respond_simple(fd, 200, "OK", "text/plain", "ok", 2,
                          cookie[0] ? cookie : NULL);
}

static int handle_restart(int fd, Request *r) {
    char cookie[256];
    Session *s = resolve_session(r, cookie, sizeof cookie);
    if (!s) return respond_simple(fd, 500, "Internal Error", "text/plain",
                                  "no session\n", 11, NULL);

    session_lock(s);
    game_reset(s->state);
    session_bump_locked(s);
    session_unlock(s);

    return respond_simple(fd, 200, "OK", "text/plain", "ok", 2,
                          cookie[0] ? cookie : NULL);
}

static int handle_game(int fd, Request *r) {
    char cookie[256];
    Session *s = resolve_session(r, cookie, sizeof cookie);
    if (!s) return -1;

    if (sse_send_headers(fd, cookie[0] ? cookie : NULL) < 0) return -1;

    unsigned long last_sent = 0;
    int idle_ticks = 0;
    /* on first connect, force-send the current frame so the browser has
     * something even before any input. */
    while (1) {
        unsigned long ver;
        char *html = NULL;
        session_lock(s);
        ver = s->version;
        if (ver != last_sent) {
            html = render_frame_html(s->state);
        }
        session_unlock(s);

        if (html) {
            int rc = sse_send_frame(fd, html);
            free(html);
            if (rc < 0) return -1;       /* client disconnected */
            last_sent = ver;
            idle_ticks = 0;
        } else {
            /* heartbeat every ~15s so reverse proxies don't drop us */
            if (++idle_ticks >= 150) {
                if (write_all(fd, ": ping\n\n", 8) < 0) return -1;
                idle_ticks = 0;
            }
        }
        /* poll cadence — 100ms is plenty for a turn-based game */
        struct timespec ts = { 0, 100 * 1000 * 1000 };
        nanosleep(&ts, NULL);
    }
}

/* ---- dispatch --------------------------------------------------------- */

void router_dispatch(int fd, Request *r) {
    if (strcmp(r->method, "GET") != 0) {
        respond_simple(fd, 405, "Method Not Allowed", "text/plain",
                       "GET only\n", 9, NULL);
        return;
    }
    if (strcmp(r->path, "/") == 0 || strcmp(r->path, "/index.html") == 0) {
        handle_index(fd);
    } else if (strcmp(r->path, "/healthz") == 0) {
        handle_health(fd);
    } else if (strcmp(r->path, "/game") == 0) {
        handle_game(fd, r);
    } else if (strcmp(r->path, "/input") == 0) {
        handle_input(fd, r);
    } else if (strcmp(r->path, "/restart") == 0) {
        handle_restart(fd, r);
    } else {
        respond_simple(fd, 404, "Not Found", "text/plain",
                       "lost in the crypt\n", 18, NULL);
    }
}
